Release v2.0.0

diff --git a/.github/workflows/validate-coding-standards.yml b/.github/workflows/validate-coding-standards.yml
--- a/.github/workflows/validate-coding-standards.yml
+++ b/.github/workflows/validate-coding-standards.yml
@@ -9,6 +9,7 @@ on:
     branches:
       - main
       - 'rc/**'
+      - 'c-coding-standards'
 
 env:
   XARGS_MAX_PROCS: 4
@@ -24,20 +25,36 @@ jobs:
       - name: Install generate_package_files.py dependencies
         run: pip install -r scripts/requirements.txt
 
-      - name: Validate Package Descriptions
+      - name: Validate Package Descriptions (CPP)
         run: |
-          python scripts/validate-rule-package.py rule_packages/*.json
+          python scripts/validate-rule-package.py rule_packages/cpp/*.json
 
-      - name: Validate Package Descriptions consistency
+      - name: Validate Package Descriptions (C)
         run: |
-          python scripts/verify_rule_package_consistency.py
+          python scripts/validate-rule-package.py rule_packages/c/*.json
 
-      - name: Validate Package Files
+      - name: Validate Package Descriptions consistency (CPP)
         run: |
-          find rule_packages/ -name \*.json -exec basename {} .json \; | xargs --max-procs "$XARGS_MAX_PROCS" --max-args 1 python3 scripts/generate_rules/generate_package_files.py
+          python scripts/verify_rule_package_consistency.py cpp
+
+      - name: Validate Package Descriptions consistency (C)
+        run: |
+          python scripts/verify_rule_package_consistency.py c
+
+      - name: Validate Package Files (CPP)
+        run: |
+          find rule_packages/cpp -name \*.json -exec basename {} .json \; | xargs --max-procs "$XARGS_MAX_PROCS" --max-args 1 python3 scripts/generate_rules/generate_package_files.py cpp
           git diff
           git diff --compact-summary
           git diff --quiet
+
+      - name: Validate Package Files (C)
+        run: |
+          find rule_packages/c -name \*.json -exec basename {} .json \; | xargs --max-procs "$XARGS_MAX_PROCS" --max-args 1 python3 scripts/generate_rules/generate_package_files.py c
+          git diff
+          git diff --compact-summary
+          git diff --quiet
+
 
   validate-codeql-format:
     name: "Validate CodeQL Format"
@@ -54,9 +71,18 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ github.token }}
 
-      - name: Validate CodeQL Format
+      - name: Validate CodeQL Format (CPP)
         run: |
           find cpp -name \*.ql -or -name \*.qll -print0 | xargs -0 --max-procs "$XARGS_MAX_PROCS" codeql/codeql query format --in-place
+
+          git diff
+          git diff --compact-summary
+          git diff --quiet
+
+      - name: Validate CodeQL Format (C)
+        run: |
+          find c -name \*.ql -or -name \*.qll -print0 | xargs -0 --max-procs "$XARGS_MAX_PROCS" codeql/codeql query format --in-place
+
           git diff
           git diff --compact-summary
           git diff --quiet
@@ -67,7 +93,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        language: ['cpp']
+        language: ['cpp', 'c']
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -119,6 +145,29 @@ jobs:
           fi
           
           find cpp/*/test -name \*.cpp -print0 | xargs -0 --max-procs "$XARGS_MAX_PROCS" clang-format --style=file -i --verbose
+          git diff
+          git diff --compact-summary
+          git diff --quiet
+
+  validate-c-test-files:
+    name: Validate C Test Files
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install clang-format
+        run: |
+          sudo apt-get install --yes --quiet --no-install-recommends clang-format
+          echo "::debug::$(clang-format -version)"
+
+      - name: Validate C++ Test Files
+        run: |
+          if ! test -f .clang-format; then
+            echo "Cannot find .clang-format in '$PWD'. Exiting..."
+          fi
+          
+          find c/*/test -name \*.c -print0 | xargs -0 --max-procs "$XARGS_MAX_PROCS" clang-format --style=file -i --verbose
           git diff
           git diff --compact-summary
           git diff --quiet
